version: '2'
services:
  mongodb:
    image: mongo:2.4
    container_name: mongodb
    ports:
     - "27017:27017"
    networks:
      - appNetwork
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
     - "5672:5672"
     - "15672:15672"
    environment:
     - RABBITMQ_DEFAULT_USER=test
     - RABBITMQ_DEFAULT_PASS=password
    networks:
      - appNetwork
  config:
    image: benwilcock/config-service
    container_name: config
    ports:
     - "8888:8888"
    environment:
     - SPRING_PROFILES_ACTIVE=production
    networks:
      - appNetwork
  discovery:
    image: benwilcock/discovery-service
    container_name: discovery
    ports:
     - "8761:8761"
    networks:
      - appNetwork
  gateway:
    image: benwilcock/gateway-service
    container_name: gateway
    ports:
     - "8080:8080"
    environment:
     - SPRING_PROFILES_ACTIVE=production
    depends_on:
     - discovery
     - config
    networks:
      - appNetwork
  product-command-side:
#    image: benwilcock/product-command-side:latest
    image: benwilcock/command-side:latest
    container_name: product-cmd-side
    depends_on:
     - mongodb
     - rabbitmq
     - discovery
     - config
    ports:
      - "9000:9000"
    environment:
     - SPRING_PROFILES_ACTIVE=production
    networks:
      - appNetwork
  product-query-side:
#    image: benwilcock/product-query-side:latest
    image: benwilcock/query-side:latest
    container_name: product-qry-side
    depends_on:
     - rabbitmq
     - discovery
     - config
    ports:
     - "9001:9001"
    environment:
     - SPRING_PROFILES_ACTIVE=production
    networks:
      - appNetwork
networks:
  appNetwork:
    external: true